name: Development build/deploy
# Controls when the workflow will run
on:
  push:
    branches-ignore: # Exclude production/release branches from the 'dev' flow
      - 'master'
      - 'main'
      - 'release/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The 'Build' job handles caching, building, and pushing the Docker image
  build:
    runs-on: soundboard-k8s-runner
    defaults:
      run:
        shell: bash

    steps:
      - name: ⚙️ Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Registry
        # Note: Secret is set on the repo itself
        uses: docker/login-action@v3
        with:
          registry: registry.codethat.rocks
          username: drone
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Dev Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: registry.codethat.rocks/soundboard/soundboard:dev-${{ github.run_number }}
          # registry.codethat.rocks/soundboard/soundboard:dev-${{ github.run_number }}
          cache-from: type=registry,ref=registry.codethat.rocks/soundboard/soundboard:buildcache
          cache-to: type=registry,ref=registry.codethat.rocks/soundboard/soundboard:buildcache,mode=max
  test:
    needs: build
    runs-on: soundboard-k8s-runner
    steps:
      - name: unit-test
        run: |
          cp /node/node_modules . -r &&
          npm install --no-optional &&
          npm test

  deploy-dev:
    if: github.event_name == 'push'
    runs-on: soundboard-k8s-runner
    defaults:
      run:
        shell: bash
    needs: [build, test] # Runs after the build job, but only if the conditions are met
    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
      - name: Update Dev Deployment image
        run: kubectl set image deployment/dev-soundboard soundboard=registry.codethat.rocks/soundboard/soundboard:dev-${{ github.run_number }} -n soundboard
